#!/bin/bash
set -euo pipefail

mariadb -u root -p"$MARIADB_ROOT_PASSWORD" <<-EOSQL
	SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';

	CREATE DATABASE IF NOT EXISTS \`camp2013\` CHARACTER SET utf8 COLLATE utf8_general_ci;
	CREATE DATABASE IF NOT EXISTS \`camp2003\` CHARACTER SET utf8 COLLATE utf8_general_ci;
	CREATE DATABASE IF NOT EXISTS \`corsi2016\` CHARACTER SET utf8 COLLATE utf8_general_ci;
	CREATE DATABASE IF NOT EXISTS \`live\` CHARACTER SET utf8 COLLATE utf8_general_ci;
	CREATE DATABASE IF NOT EXISTS \`refertoelettronico\` CHARACTER SET utf8 COLLATE utf8_general_ci;
	CREATE DATABASE IF NOT EXISTS \`vnl_ticketing\` CHARACTER SET utf8 COLLATE utf8_general_ci;

	GRANT ALL PRIVILEGES ON \`camp2013\`.* TO '$MARIADB_USER'@'%';
	GRANT ALL PRIVILEGES ON \`camp2003\`.* TO '$MARIADB_USER'@'%';
	GRANT ALL PRIVILEGES ON \`corsi2016\`.* TO '$MARIADB_USER'@'%';
	GRANT ALL PRIVILEGES ON \`live\`.* TO '$MARIADB_USER'@'%';
	GRANT ALL PRIVILEGES ON \`refertoelettronico\`.* TO '$MARIADB_USER'@'%';
	GRANT ALL PRIVILEGES ON \`vnl_ticketing\`.* TO '$MARIADB_USER'@'%';

	FLUSH PRIVILEGES;
EOSQL
